// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: pkg/msg/msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WspCmd int32

const (
	WspCmd_CONNECT   WspCmd = 0
	WspCmd_RESPOND   WspCmd = 1
	WspCmd_TRANSFER  WspCmd = 2
	WspCmd_INTERRUPT WspCmd = 3
)

// Enum value maps for WspCmd.
var (
	WspCmd_name = map[int32]string{
		0: "CONNECT",
		1: "RESPOND",
		2: "TRANSFER",
		3: "INTERRUPT",
	}
	WspCmd_value = map[string]int32{
		"CONNECT":   0,
		"RESPOND":   1,
		"TRANSFER":  2,
		"INTERRUPT": 3,
	}
)

func (x WspCmd) Enum() *WspCmd {
	p := new(WspCmd)
	*p = x
	return p
}

func (x WspCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WspCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_msg_msg_proto_enumTypes[0].Descriptor()
}

func (WspCmd) Type() protoreflect.EnumType {
	return &file_pkg_msg_msg_proto_enumTypes[0]
}

func (x WspCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WspCmd.Descriptor instead.
func (WspCmd) EnumDescriptor() ([]byte, []int) {
	return file_pkg_msg_msg_proto_rawDescGZIP(), []int{0}
}

type WspType int32

const (
	WspType_LOCAL   WspType = 0
	WspType_REMOTE  WspType = 1
	WspType_DYNAMIC WspType = 2
)

// Enum value maps for WspType.
var (
	WspType_name = map[int32]string{
		0: "LOCAL",
		1: "REMOTE",
		2: "DYNAMIC",
	}
	WspType_value = map[string]int32{
		"LOCAL":   0,
		"REMOTE":  1,
		"DYNAMIC": 2,
	}
)

func (x WspType) Enum() *WspType {
	p := new(WspType)
	*p = x
	return p
}

func (x WspType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WspType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_msg_msg_proto_enumTypes[1].Descriptor()
}

func (WspType) Type() protoreflect.EnumType {
	return &file_pkg_msg_msg_proto_enumTypes[1]
}

func (x WspType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WspType.Descriptor instead.
func (WspType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_msg_msg_proto_rawDescGZIP(), []int{1}
}

type WspCode int32

const (
	WspCode_FAILED  WspCode = 0
	WspCode_SUCCESS WspCode = 1
)

// Enum value maps for WspCode.
var (
	WspCode_name = map[int32]string{
		0: "FAILED",
		1: "SUCCESS",
	}
	WspCode_value = map[string]int32{
		"FAILED":  0,
		"SUCCESS": 1,
	}
)

func (x WspCode) Enum() *WspCode {
	p := new(WspCode)
	*p = x
	return p
}

func (x WspCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WspCode) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_msg_msg_proto_enumTypes[2].Descriptor()
}

func (WspCode) Type() protoreflect.EnumType {
	return &file_pkg_msg_msg_proto_enumTypes[2]
}

func (x WspCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WspCode.Descriptor instead.
func (WspCode) EnumDescriptor() ([]byte, []int) {
	return file_pkg_msg_msg_proto_rawDescGZIP(), []int{2}
}

type WspMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cmd  WspCmd `protobuf:"varint,2,opt,name=cmd,proto3,enum=WspCmd" json:"cmd,omitempty"`
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *WspMessage) Reset() {
	*x = WspMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_msg_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WspMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WspMessage) ProtoMessage() {}

func (x *WspMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_msg_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WspMessage.ProtoReflect.Descriptor instead.
func (*WspMessage) Descriptor() ([]byte, []int) {
	return file_pkg_msg_msg_proto_rawDescGZIP(), []int{0}
}

func (x *WspMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WspMessage) GetCmd() WspCmd {
	if x != nil {
		return x.Cmd
	}
	return WspCmd_CONNECT
}

func (x *WspMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WspRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type WspType `protobuf:"varint,1,opt,name=type,proto3,enum=WspType" json:"type,omitempty"`
	Data string  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *WspRequest) Reset() {
	*x = WspRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_msg_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WspRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WspRequest) ProtoMessage() {}

func (x *WspRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_msg_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WspRequest.ProtoReflect.Descriptor instead.
func (*WspRequest) Descriptor() ([]byte, []int) {
	return file_pkg_msg_msg_proto_rawDescGZIP(), []int{1}
}

func (x *WspRequest) GetType() WspType {
	if x != nil {
		return x.Type
	}
	return WspType_LOCAL
}

func (x *WspRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type WspResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code WspCode `protobuf:"varint,1,opt,name=code,proto3,enum=WspCode" json:"code,omitempty"`
	Data string  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *WspResponse) Reset() {
	*x = WspResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_msg_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WspResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WspResponse) ProtoMessage() {}

func (x *WspResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_msg_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WspResponse.ProtoReflect.Descriptor instead.
func (*WspResponse) Descriptor() ([]byte, []int) {
	return file_pkg_msg_msg_proto_rawDescGZIP(), []int{2}
}

func (x *WspResponse) GetCode() WspCode {
	if x != nil {
		return x.Code
	}
	return WspCode_FAILED
}

func (x *WspResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_pkg_msg_msg_proto protoreflect.FileDescriptor

var file_pkg_msg_msg_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x0a, 0x57, 0x73, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x19, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07,
	0x2e, 0x57, 0x73, 0x70, 0x43, 0x6d, 0x64, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x3e, 0x0a, 0x0a, 0x57, 0x73, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x57,
	0x73, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x3f, 0x0a, 0x0b, 0x57, 0x73, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e,
	0x57, 0x73, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x2a, 0x3f, 0x0a, 0x06, 0x57, 0x73, 0x70, 0x43, 0x6d, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x43,
	0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x53, 0x50,
	0x4f, 0x4e, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x46, 0x45,
	0x52, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x52, 0x55, 0x50, 0x54,
	0x10, 0x03, 0x2a, 0x2d, 0x0a, 0x07, 0x57, 0x73, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a,
	0x05, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x4d, 0x4f,
	0x54, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x59, 0x4e, 0x41, 0x4d, 0x49, 0x43, 0x10,
	0x02, 0x2a, 0x22, 0x0a, 0x07, 0x57, 0x73, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0a, 0x0a, 0x06,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43,
	0x45, 0x53, 0x53, 0x10, 0x01, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x77, 0x73, 0x70, 0x2f, 0x77, 0x73, 0x70, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_msg_msg_proto_rawDescOnce sync.Once
	file_pkg_msg_msg_proto_rawDescData = file_pkg_msg_msg_proto_rawDesc
)

func file_pkg_msg_msg_proto_rawDescGZIP() []byte {
	file_pkg_msg_msg_proto_rawDescOnce.Do(func() {
		file_pkg_msg_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_msg_msg_proto_rawDescData)
	})
	return file_pkg_msg_msg_proto_rawDescData
}

var file_pkg_msg_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_msg_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_msg_msg_proto_goTypes = []interface{}{
	(WspCmd)(0),         // 0: WspCmd
	(WspType)(0),        // 1: WspType
	(WspCode)(0),        // 2: WspCode
	(*WspMessage)(nil),  // 3: WspMessage
	(*WspRequest)(nil),  // 4: WspRequest
	(*WspResponse)(nil), // 5: WspResponse
}
var file_pkg_msg_msg_proto_depIdxs = []int32{
	0, // 0: WspMessage.cmd:type_name -> WspCmd
	1, // 1: WspRequest.type:type_name -> WspType
	2, // 2: WspResponse.code:type_name -> WspCode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_msg_msg_proto_init() }
func file_pkg_msg_msg_proto_init() {
	if File_pkg_msg_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_msg_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WspMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_msg_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WspRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_msg_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WspResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_msg_msg_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_msg_msg_proto_goTypes,
		DependencyIndexes: file_pkg_msg_msg_proto_depIdxs,
		EnumInfos:         file_pkg_msg_msg_proto_enumTypes,
		MessageInfos:      file_pkg_msg_msg_proto_msgTypes,
	}.Build()
	File_pkg_msg_msg_proto = out.File
	file_pkg_msg_msg_proto_rawDesc = nil
	file_pkg_msg_msg_proto_goTypes = nil
	file_pkg_msg_msg_proto_depIdxs = nil
}
